In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('../ml-exploratory-data-analysis/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df=df[['Age','Name','Pclass','SibSp','Parch','Survived']]

In [4]:
df.head()

,Age,Name,Pclass,SibSp,Parch,Survived
0,22.0,"Braund, Mr. Owen Harris",3,1,0,0
1,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,0,1
2,26.0,"Heikkinen, Miss. Laina",3,0,0,1
3,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,0,1
4,35.0,"Allen, Mr. William Henry",3,0,0,0

In [5]:
df=df.dropna()

In [6]:
X=df.iloc[:,0:5]
y=df.iloc[:,-1]

<h2><b>Applying Feature Construction

In [8]:
X['family_size']=X['SibSp']+X['Parch']+1
X.head()

,Age,Name,Pclass,SibSp,Parch,family_size
0,22.0,"Braund, Mr. Owen Harris",3,1,0,2
1,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,0,2
2,26.0,"Heikkinen, Miss. Laina",3,0,0,1
3,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,0,2
4,35.0,"Allen, Mr. William Henry",3,0,0,1

Can help improve accuracy